using System.Text;
using NUnit.Framework;
using Chimera.Runtime;

namespace Chimera.Runtime.Tests
{
    public class PlyParserTests
    {
        private static byte[] AsciiHeader =>
            Encoding.ASCII.GetBytes(string.Join("\n", new[]
            {
                "ply",
                "format ascii 1.0",
                "comment generated by tests",
                "element vertex 3",
                "property float x",
                "property float y",
                "property float z",
                "end_header",
                "",
            }));

        [Test]
        public void ParseHeader_ParsesAsciiVertexElement()
        {
            var header = PlyParser.ParseHeader(AsciiHeader);
            Assert.AreEqual(PlyFormat.Ascii, header.Format);
            var vertex = header.FindElement("vertex");
            Assert.IsNotNull(vertex);
            Assert.AreEqual(3, vertex.Count);
            Assert.AreEqual(3, vertex.Properties.Count);
            Assert.AreEqual("x", vertex.Properties[0].Name);
        }

        [Test]
        public void VertexStride_SumsScalarSizes()
        {
            var header = PlyParser.ParseHeader(AsciiHeader);
            int stride = PlyParser.VertexStride(header.FindElement("vertex"));
            Assert.AreEqual(12, stride); // three float32
        }

        [Test]
        public void ScalarSize_KnownTypes()
        {
            Assert.AreEqual(1, PlyParser.ScalarSize("uchar"));
            Assert.AreEqual(2, PlyParser.ScalarSize("ushort"));
            Assert.AreEqual(4, PlyParser.ScalarSize("float"));
            Assert.AreEqual(8, PlyParser.ScalarSize("double"));
        }
    }
}
