"""initial schema

Revision ID: 8a28d65d2f13
Revises: 
Create Date: 2026-05-07 18:31:06.094510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a28d65d2f13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('script_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=True),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('evidence_chunk_ids_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tts_asset_id', sa.String(length=36), nullable=True),
    sa.Column('duration_estimate_sec', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['poster_panels.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tts_asset_id'], ['tts_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_segments_language'), 'script_segments', ['language'], unique=False)
    op.create_index(op.f('ix_script_segments_profile'), 'script_segments', ['profile'], unique=False)
    op.create_index(op.f('ix_script_segments_session_id'), 'script_segments', ['session_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('presenter_name', sa.String(length=120), nullable=True),
    sa.Column('presenter_name_kana', sa.String(length=120), nullable=True),
    sa.Column('presenter_affiliation', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('session_code', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_code')
    )
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    op.create_table('tts_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('voice_id', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['script_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_assets_asset_id'), 'tts_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_tts_assets_cache_key'), 'tts_assets', ['cache_key'], unique=False)
    op.create_index(op.f('ix_tts_assets_segment_id'), 'tts_assets', ['segment_id'], unique=False)
    op.create_index(op.f('ix_tts_assets_session_id'), 'tts_assets', ['session_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_session_id'), 'assets', ['session_id'], unique=False)
    op.create_table('evidence_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('support_status', sa.String(length=32), nullable=False),
    sa.Column('evidence_chunk_ids_json', sa.Text(), nullable=False),
    sa.Column('limitation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claims_session_id'), 'evidence_claims', ['session_id'], unique=False)
    op.create_table('poster_panels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'label', name='uq_poster_panels_session_label')
    )
    op.create_index(op.f('ix_poster_panels_session_id'), 'poster_panels', ['session_id'], unique=False)
    op.create_table('presentation_cues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=True),
    sa.Column('cue_type', sa.String(length=32), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_cues_session_id'), 'presentation_cues', ['session_id'], unique=False)
    op.create_table('voice_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('voice_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('confirmed_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('consent_label', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_consents_session_id'), 'voice_consents', ['session_id'], unique=False)
    op.create_index(op.f('ix_voice_consents_voice_id'), 'voice_consents', ['voice_id'], unique=False)
    op.create_table('avatar_build_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('source_ply_asset_id', sa.String(length=36), nullable=True),
    sa.Column('source_vrm_asset_id', sa.String(length=36), nullable=True),
    sa.Column('output_asset_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['output_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_ply_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['source_vrm_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_build_jobs_session_id'), 'avatar_build_jobs', ['session_id'], unique=False)
    op.create_table('avatar_configs',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('runtime_type', sa.String(length=32), nullable=False),
    sa.Column('gvrm_asset_id', sa.String(length=36), nullable=True),
    sa.Column('source_ply_asset_id', sa.String(length=36), nullable=True),
    sa.Column('source_vrm_asset_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('attribution', sa.String(length=512), nullable=True),
    sa.Column('license_note', sa.String(length=512), nullable=True),
    sa.Column('placement_position_json', sa.Text(), nullable=False),
    sa.Column('placement_rotation_json', sa.Text(), nullable=False),
    sa.Column('placement_scale', sa.Float(), nullable=False),
    sa.Column('default_animation', sa.String(length=80), nullable=False),
    sa.Column('behavior_idle', sa.String(length=80), nullable=False),
    sa.Column('behavior_explain', sa.String(length=80), nullable=False),
    sa.Column('behavior_listening', sa.String(length=80), nullable=False),
    sa.Column('behavior_thinking', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gvrm_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_ply_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['source_vrm_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trust_level', sa.String(length=32), nullable=False),
    sa.Column('use_for_script', sa.Boolean(), nullable=False),
    sa.Column('use_for_live_qa', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('citation_label', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_session_id'), 'knowledge_documents', ['session_id'], unique=False)
    op.create_table('poster_configs',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('poster_asset_id', sa.String(length=36), nullable=True),
    sa.Column('poster_format', sa.String(length=16), nullable=False),
    sa.Column('orientation', sa.String(length=16), nullable=False),
    sa.Column('physical_width_m', sa.Float(), nullable=False),
    sa.Column('physical_height_m', sa.Float(), nullable=False),
    sa.Column('tracking_reference_name', sa.String(length=255), nullable=True),
    sa.Column('qr_fallback_enabled', sa.Boolean(), nullable=False),
    sa.Column('qr_asset_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['poster_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['qr_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('poster_text_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poster_text_blocks_asset_id'), 'poster_text_blocks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_poster_text_blocks_session_id'), 'poster_text_blocks', ['session_id'], unique=False)
    op.create_table('simulated_qas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('evidence_chunk_ids_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('question_embedding_json', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('embedding_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['poster_panels.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulated_qas_language'), 'simulated_qas', ['language'], unique=False)
    op.create_index(op.f('ix_simulated_qas_profile'), 'simulated_qas', ['profile'], unique=False)
    op.create_index(op.f('ix_simulated_qas_session_id'), 'simulated_qas', ['session_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('embedding_status', sa.String(length=32), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('retrieval_enabled', sa.Boolean(), nullable=False),
    sa.Column('script_enabled', sa.Boolean(), nullable=False),
    sa.Column('qa_enabled', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['panel_id'], ['poster_panels.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_session_id'), 'knowledge_chunks', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_session_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_simulated_qas_session_id'), table_name='simulated_qas')
    op.drop_index(op.f('ix_simulated_qas_profile'), table_name='simulated_qas')
    op.drop_index(op.f('ix_simulated_qas_language'), table_name='simulated_qas')
    op.drop_table('simulated_qas')
    op.drop_index(op.f('ix_poster_text_blocks_session_id'), table_name='poster_text_blocks')
    op.drop_index(op.f('ix_poster_text_blocks_asset_id'), table_name='poster_text_blocks')
    op.drop_table('poster_text_blocks')
    op.drop_table('poster_configs')
    op.drop_index(op.f('ix_knowledge_documents_session_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_table('avatar_configs')
    op.drop_index(op.f('ix_avatar_build_jobs_session_id'), table_name='avatar_build_jobs')
    op.drop_table('avatar_build_jobs')
    op.drop_index(op.f('ix_voice_consents_voice_id'), table_name='voice_consents')
    op.drop_index(op.f('ix_voice_consents_session_id'), table_name='voice_consents')
    op.drop_table('voice_consents')
    op.drop_index(op.f('ix_presentation_cues_session_id'), table_name='presentation_cues')
    op.drop_table('presentation_cues')
    op.drop_index(op.f('ix_poster_panels_session_id'), table_name='poster_panels')
    op.drop_table('poster_panels')
    op.drop_index(op.f('ix_evidence_claims_session_id'), table_name='evidence_claims')
    op.drop_table('evidence_claims')
    op.drop_index(op.f('ix_assets_session_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_tts_assets_session_id'), table_name='tts_assets')
    op.drop_index(op.f('ix_tts_assets_segment_id'), table_name='tts_assets')
    op.drop_index(op.f('ix_tts_assets_cache_key'), table_name='tts_assets')
    op.drop_index(op.f('ix_tts_assets_asset_id'), table_name='tts_assets')
    op.drop_table('tts_assets')
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_script_segments_session_id'), table_name='script_segments')
    op.drop_index(op.f('ix_script_segments_profile'), table_name='script_segments')
    op.drop_index(op.f('ix_script_segments_language'), table_name='script_segments')
    op.drop_table('script_segments')
    op.drop_table('app_users')
    # ### end Alembic commands ###
